version: '3'
services:
  #Posts Service
  posts-service:
    image: vjv2143/kwetter.posts-service
    container_name: posts-service
    ports:
      - ${POSTS_SERVICE_PORT}:4000
    networks:
      - network-name
    environment:
      PORT: ${POSTS_SERVICE_PORT}

  #Mentions Service
  mentions-service:
    image: vjv2143/kwetter.mentions-service
    container_name: mentions-service
    ports:
      - ${MENTIONS_SERVICE_PORT}:4000
    networks:
      - network-name
    environment:
      PORT: ${MENTIONS_SERVICE_PORT}

  #NATS Streaming
  nast-streaming:
    image: nats-streaming:0.17.0
    container_name: nats-streaming
    ports:
      - ${NATS_PORT}:4222
      - ${NATS_MONITORING_PORT}:8222

networks:
  network-name:
    name: swsp
