version: '3'
services:
  #Posts Service
  posts-service:
    image: vjv2143/kwetter.posts-service
    container_name: posts-service
    ports:
      - ${POST_SERVICE_PORT}:80
    networks:
      - network-name
    environment:
      PORT: ${POST_SERVICE_PORT}

  #NATS Streaming
  nast-streaming:
    immage: nats-streaming:0.17.0
    container_name: nats-streaming
    ports:
      - ${NATS_PORT}:4222
      - ${NATS_MONITORING_PORT}:8222

networks:
  network-name:
    name: swsp
