version: '3'
services:
  #Posts Service
  posts-service:
    image: vjv2143/kwetter.posts-service
    container_name: posts-service
    ports:
      - ${POSTS_SERVICE_PORT}:4000
    networks:
      - network-name
    environment:
      PORT: ${POSTS_SERVICE_PORT}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      NATS_CLIENT_ID: ${NATS_POST_SERVICE_CLIENT_ID}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_POST_CREATED_CHANNEL: ${NATS_POST_CREATED_CHANNEL}

  #Mentions Service
  mentions-service:
    image: vjv2143/kwetter.mentions-service
    container_name: mentions-service
    ports:
      - ${MENTIONS_SERVICE_PORT}:4000
    networks:
      - network-name
    environment:
      PORT: ${MENTIONS_SERVICE_PORT}
      NATS_CLUSTER_ID: ${NATS_CLUSTER_ID}
      NATS_CLIENT_ID: ${NATS_MENTIONS_SERVICE_CLIENT_ID}
      NATS_HOST: ${NATS_HOST}
      NATS_PORT: ${NATS_PORT}
      NATS_POST_CREATED_CHANNEL: ${NATS_POST_CREATED_CHANNEL}
      NATS_DURABLE_NAME: ${NATS_MENTIONS_SERVICE_DURABLE_NAME}
      NATS_QUEUE_GROUP: ${NATS_MENTIONS_SERVICE_QUEUE_GROUP}

  #NATS Streaming
  nats-streaming:
    image: nats-streaming:0.17.0
    container_name: nats-streaming
    ports:
      - ${NATS_PORT}:4222
      - ${NATS_MONITORING_PORT}:8222

networks:
  network-name:
    name: kwetter
