version: '3'
services:
  #Gateway
  gateway:
    image: vasilvelikovkwetter.azurecr.io/gateway
    container_name: gateway
    depends_on:
      - nats-streaming
    env_file: .gateway.env
    ports:
      - ${GATEWAY_PORT}:4000
    networks:
      - network-name

  #Accounts Service
  accounts-service:
    image: vasilvelikovkwetter.azurecr.io/accounts-service
    container_name: accounts-service
    depends_on:
      - nats-streaming
    env_file: .accounts.env
    networks:
      - network-name

  #Posts Service
  posts-service:
    image: vasilvelikovkwetter.azurecr.io/posts-service
    container_name: posts-service
    depends_on:
      - nats-streaming
    env_file: .posts.env
    networks:
      - network-name

  #Mentions Service
  mentions-service:
    image: vasilvelikovkwetter.azurecr.io/mentions-service
    container_name: mentions-service
    depends_on:
      - nats-streaming
    env_file: .mentions.env
    networks:
      - network-name

  #Mentioning Posts Service
  mentioning-posts-service:
    image: vasilvelikovkwetter.azurecr.io/mentioning-posts-service
    container_name: mentioning-posts-service
    depends_on:
      - nats-streaming
    env_file: .mentioning-posts.env
    networks:
      - network-name

  #NATS Streaming
  nats-streaming:
    image: nats-streaming:0.17.0
    container_name: nats-streaming
    ports:
      - ${NATS_MONITORING_PORT}:8222
    networks:
      - network-name

networks:
  network-name:
    name: kwetter
