version: '3'
services:
  #Gateway
  gateway:
    image: vasilvelikovkwetter.azurecr.io/gateway
    container_name: gateway
    depends_on:
      - nats-streaming
    env_file: .gateway.env
    ports:
      - ${GATEWAY_PORT}:4000
    networks:
      - network-name

  #Accounts Service
  accounts:
    image: vasilvelikovkwetter.azurecr.io/accounts
    container_name: accounts
    depends_on:
      - nats-streaming
    env_file: .accounts.env
    networks:
      - network-name

  #Posts Service
  posts:
    image: vasilvelikovkwetter.azurecr.io/posts
    container_name: posts
    depends_on:
      - nats-streaming
    env_file: .posts.env
    networks:
      - network-name

  #Mentions Service
  mentions:
    image: vasilvelikovkwetter.azurecr.io/mentions
    container_name: mentions
    depends_on:
      - nats-streaming
    env_file: .mentions.env
    networks:
      - network-name

  #Mentioning Posts Service
  mentioning-posts:
    image: vasilvelikovkwetter.azurecr.io/mentions-posts
    container_name: mentions-posts
    depends_on:
      - nats-streaming
    env_file: .mentioning-posts.env
    networks:
      - network-name

  #NATS Streaming
  nats-streaming:
    image: nats-streaming:0.17.0
    container_name: nats-streaming
    ports:
      - ${NATS_MONITORING_PORT}:8222
    networks:
      - network-name

networks:
  network-name:
    name: kwetter
