version: '3'
services:
  #Gateway
  gateway:
    image: vjv2143/kwetter.gateway
    container_name: gateway
    depends_on:
      - nats-streaming
    env_file: .gateway.env
    ports:
      - ${GATEWAY_PORT}:4000
    networks:
      - network-name

  #Accounts Service
  accounts:
    image: vjv2143/kwetter.accounts
    container_name: accounts
    depends_on:
      - nats-streaming
    env_file: .accounts.env
    networks:
      - network-name

  #Details Service
  details:
    image: vjv2143/kwetter.details
    container_name: details
    depends_on:
      - nats-streaming
    env_file: .details.env
    networks:
      - network-name

  #Following Service
  following:
    image: vjv2143/kwetter.following
    container_name: following
    depends_on:
      - nats-streaming
    env_file: .following.env
    networks:
      - network-name

  #Likes Service
  likes:
    image: vjv2143/kwetter.likes
    container_name: likes
    depends_on:
      - nats-streaming
    env_file: .likes.env
    networks:
      - network-name

  #Mentioning Posts Service
  mentioning-posts:
    image: vjv2143/kwetter.mentioning_posts
    container_name: mentioning-posts
    depends_on:
      - nats-streaming
    env_file: .mentioning-posts.env
    networks:
      - network-name

  #Mentions Service
  mentions:
    image: vjv2143/kwetter.mentions
    container_name: mentions
    depends_on:
      - nats-streaming
    env_file: .mentions.env
    networks:
      - network-name

  #Pictures Service
  pictures:
    image: vjv2143/kwetter.pictures
    container_name: pictures
    depends_on:
      - nats-streaming
    env_file: .pictures.env
    networks:
      - network-name

  #Posts Service
  posts:
    image: vjv2143/kwetter.posts
    container_name: posts
    depends_on:
      - nats-streaming
    env_file: .posts.env
    networks:
      - network-name

  #Timeline Service
  timeline:
    image: vjv2143/kwetter.timeline
    container_name: timeline
    depends_on:
      - nats-streaming
    env_file: .timeline.env
    networks:
      - network-name

  #Trend Posts Service
  trend-posts:
    image: vjv2143/kwetter.trend_posts
    container_name: trend-posts
    depends_on:
      - nats-streaming
    env_file: .trend-posts.env
    networks:
      - network-name

  #Trends Service
  trends:
    image: vjv2143/kwetter.trends
    container_name: trends
    depends_on:
      - nats-streaming
    env_file: .trends.env
    networks:
      - network-name

  #Users Service
  users:
    image: vjv2143/kwetter.users
    container_name: users
    depends_on:
      - nats-streaming
    env_file: .users.env
    networks:
      - network-name

  #NATS Streaming
  nats-streaming:
    image: nats-streaming:0.17.0
    container_name: nats-streaming
    ports:
      - 4222:4222
      - ${NATS_MONITORING_PORT}:8222
    networks:
      - network-name

networks:
  network-name:
    name: kwetter
