apiVersion: v1
kind: Secret
metadata:
  name: following-secret
type: Opaque
data:
  FIRESTORE_SERVICE_PASSWORD: biAwZGIzZDVhNmJiYTFmNDlkMzQyOGZhYjE4ZGYzYzA4YWUxMjhjOWFkMzM1ZmM5YjExMDljYmI3NWJkYjBiNGM3YTkwMWJmZWZkNzY0NGQyZWFjOWNjNmNkOTJiMjk3ZThkZTU3OGQ1ZDVmOWUxZWQzYmIxNWY1YzBiYWFhNTgxMQo=
