apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
data:
  JWT_SECRET: ZDhmY2I5M2IwMmM4ZGRlNzM4OTE4ZjQ2OTU3MjQ2ZWFkMjFhZWM5YjQ1NjdjZDllYzU1MjgzNDY3NDU5MThjZGVjN2MwNmYyMzM0ZjE1ODdlMGQyM2JmY2NhM2MxNmE5ZWYxOWMyNTYyNTEzYjhhODM0Nzg4N2I2MjIwOWQ1Mjk=
