apiVersion: v1
kind: Secret
metadata:
  name: gateway-secret
type: Opaque
data:
  JWT_SECRET: biBiMWNkOWM5OWQxNzExMWFkOWI2ZGIzZmVjMDEwMjFlMGMxMjhmOTg5ZDliMmM3NTc5MjdhMjg5ZGI3NjA1N2VhYWFiN2Q3NjZmOTA2MjM0NmVjYzE1YTQ4M2YwMjc3ZDE4YzQ4OGY4MGIyMjg2M2Q4YzUxYjU5YTYzMjQ3ODM1OAo=
