apiVersion: v1
kind: Secret
metadata:
  name: likes-secret
type: Opaque
data:
  FIRESTORE_SERVICE_PASSWORD: MDViZmVhMTI1YzBkZDMwNjdhMjAxZmU1YTJkYTk3MGY0YmIzZTUwNjU1MjQzYWNlZGFmYzVhNjBjYTg1MDZiZTRjNWI0ZWQyZDI5NDcyOGI1NGFiMjg2NjE4NTE2YjgzOWRlMjM2M2JmZDA5MTI3NGUwYmU4MjliOTU0YTVlODM=
