apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
  labels:
    app: users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: kwetteracr.azurecr.io/users:staging
          ports:
            - containerPort: 4000
          env:
            - name: FIRESTORE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: FIRESTORE_API_KEY

            - name: FIRESTORE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: FIRESTORE_AUTH_DOMAIN

            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: FIRESTORE_PROJECT_ID

            - name: FIRESTORE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: FIRESTORE_STORAGE_BUCKET

            - name: FIRESTORE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: FIRESTORE_MESSAGING_SENDER_ID

            - name: FIRESTORE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: FIRESTORE_APP_ID

            - name: FIRESTORE_SERVICE_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: FIRESTORE_SERVICE_EMAIL

            - name: FIRESTORE_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: users-secret
                  key: FIRESTORE_SERVICE_PASSWORD

            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: CLUSTER_ID

            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: URL

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_DURABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: NATS_DURABLE_NAME

            - name: NATS_QUEUE_GROUP
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: NATS_QUEUE_GROUP

            - name: NATS_ACCOUNT_CREATED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: ACCOUNT_CREATED_CHANNEL

            - name: NATS_PICTURE_ADDED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: PICTURE_ADDED_CHANNEL

            - name: NATS_DETAILS_ADDED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: DETAILS_ADDED_CHANNEL

            - name: NATS_ACCOUNT_PROMOTED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: ACCOUNT_PROMOTED_CHANNEL

            - name: NATS_ACCOUNT_DEMOTED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: ACCOUNT_DEMOTED_CHANNEL

            - name: NATS_ACCOUNT_DELETED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: ACCOUNT_DELETED_CHANNEL
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: users
  ports:
    - protocol: TCP
      port: 4011
      targetPort: 4000
