apiVersion: v1
kind: Secret
metadata:
  name: users-secret
type: Opaque
data:
  FIRESTORE_SERVICE_PASSWORD: NzYxNzcxMzgxYzExMmVmZWQ3Yjk1NDMzMTc1MjA4ZTNhODRhZDU5N2ZmMzQ2MTg2MGMxYjg4MDQ1ZGU4ZWVkMjZlNmNjOGJmN2FhODQ4NGY2ZjVlMWZjNDRmMTQ4ZDAwMWFiMzk2YmE3NmE4OWM2ZjU3M2JmMTI0ZDZhNmM1ZmU=

