apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-db-configmap
data:
  api-key: "AIzaSyBnHS1iNI3mxaGHeMAh1XH2-lbS_MvqjXg"
  auth-domain: "kwetter-posts.firebaseapp.com"
  project-id: "kwetter-posts"
  storage-bucket: "kwetter-posts.appspot.com"
  messaging-sender-id: "578340542785"
  app-id: "1:578340542785:web:a986dd952994c0eada29c0"
