apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-db-configmap
data:
  firebase:
    api-key: AIzaSyBnHS1iNI3mxaGHeMAh1XH2-lbS_MvqjXg
    auth-domain: kwetter-posts.firebaseapp.com
    project-id: kwetter-posts
    storage-bucket: kwetter-posts.appspot.com
    messaging-senderId: 578340542785
    app-id: 1:578340542785:web:a986dd952994c0eada29c0
