export const SET_AUTH = "SET_AUTH";
export const SET_AUTH_LOADING = "SET_AUTH_LOADING";
export const SET_AUTH_ERROR = "SET_AUTH_ERROR";

export const SET_USER = "SET_USER";
export const SET_USER_LOADING = "SET_USER_LOADING";
export const SET_USER_ERROR = "SET_USER_ERROR";

export const SET_USER_POSTS = "SET_USER_POSTS";
export const SET_USER_POSTS_LOADING = "SET_USER_POSTS_LOADING";
export const SET_USER_POSTS_ERROR = "SET_USER_POSTS_ERROR";

export const SET_MENTIONS = "SET_MENTIONS";
export const SET_MENTIONS_LOADING = "SET_MENTIONS_LOADING";
export const SET_MENTIONS_ERROR = "SET_MENTIONS_ERROR";

export const SET_FOLLOWING = "SET_MENTIONS";
export const SET_FOLLOWING_LOADING = "SET_USER_POSTS_LOADING";
export const SET_FOLLOWING_ERROR = "SET_FOLLOWING_ERROR";

export const SET_FOLLOWERS = "SET_FOLLOWERS";
export const SET_FOLLOWERS_LOADING = "SET_FOLLOWERS_LOADING";
export const SET_FOLLOWERS_ERROR = "SET_FOLLOWERS_ERROR";

export const SET_TIMELINE_POSTS = "SET_TIMELINE_POSTS";
export const SET_TIMELINE_POSTS_LOADING = "SET_TIMELINE_POSTS_LOADING";
export const SET_TIMELINE_POSTS_ERROR = "SET_TIMELINE_POSTS_ERROR";

export const SET_LIKE_LOADING = "SET_LIKE_LOADING";
export const SET_LIKE_ERROR = "SET_LIKE_ERROR";
