name: Accounts

on:
  push:
    branches: [master]
    paths: 'src/accounts/**'

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: vasilvelikovkwetter.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build ./src/accounts -t vasilvelikovkwetter.azurecr.io/accounts-service:latest
          docker push vasilvelikovkwetter.azurecr.io/accounts-service:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
