name: Main

on: push

jobs:
  setup:
    name: Get Updated Paths
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.paths }}
    steps:
      - uses: actions/checkout@v1

      - id: matrix
        run: |
          pathArray=()
          for updatedFile in "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          do
            if [[ $updatedFile == src\/* ]]
              then
              temporaryString=${updatedFile#*/}
              path=${temporaryString%/*}
              pathArray+=($path)
            fi
          done
          echo ::set-output name=paths::${pathArray[@]}

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        paths: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.paths }}"
