name: Main

on: push

jobs:
  setup:
    name: Get Updated Paths
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.paths }}
    steps:
      - uses: actions/checkout@v2

#      - id: matrix
#        run: |
#          echo '::set-output name=value::[\"a\", \"b\", \"c\"]'

      - run: |
          echo $(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})
          arr=()
          for i in "$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }})"
          do
            arr+=($i)
            echo $i
          done
          echo ${arr[@]}
          echo ::set-output name=paths::${arr[@]}

  build:
    needs: setup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJson(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.paths }}"
