name: Mentions

on:
  push:
    branches: [master]
    paths: 'src/mentions/**'

jobs:
  sonar:
    name: Scan With Sonarqube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./src/mentions
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MENTIONS }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_MENTIONS }}

  build:
    name: Build Docker image and push to ACR
    runs-on: ubuntu-latest
    needs: sonar
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: vasilvelikovkwetter.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and Push Image
        run: |
          docker build ./src/mentions -t vasilvelikovkwetter.azurecr.io/mentions:latest
          docker push vasilvelikovkwetter.azurecr.io/mentions:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
