name: Mentioning Posts

on:
  push:
    branches: [master]
    paths: 'src/mentioning-posts/**'

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/mentioning-posts
          tags: vjv2143/kwetter.mentioning-posts-service:latest
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Login to Azure Container Registry, Build and Push Image
        uses: azure/docker-login@v1
        with:
          login-server: vasilvelikovkwetter.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
        run: |
          docker build ./src/mentioning-posts -t vasilvelikovkwetter.azurecr.io/mentioning-posts-service:${{ github.sha }}
          docker push vasilvelikovkwetter.azurecr.io/mentioning-posts-service:${{ github.sha }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
