name: Posts Dev

on:
  push:
    branches: [dev]
    paths: 'src/posts/**'

jobs:
  build-and-push-docker-image:
    name: Build Docker image and push to DockerHub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
          id: buildx
          uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: ./src/posts

          tags: vjv2143/kwetter.posts:latest

          push: ${{ github.ref == 'refs/heads/dev' }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
