name: Web App

on:
  push:
    paths: 'src/web-app/**'

jobs:
  test:
    name: Test with Jest
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 'src/accounts'
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12'
          cache: 'npm'
          cache-dependency-path: src/accounts/package-lock.json

      - name: Install dependencies with npm
        run: npm install

      - name: Run tests and generate coverage
        run: npm run test:ci

      - name: Create coverage artifact
        if: ${{ success() }}
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: |
            src/accounts/coverage/lcov.info
            src/accounts/coverage/test-reporter.xml

      - name: Tests ✅
        if: ${{ success() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "success",
            "description": "Tests passed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

      - name: Tests 🚨
        if: ${{ failure() }}
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "context": "tests",
            "state": "failure",
            "description": "Tests failed",
            "target_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }'

  sonar:
    name: Scan With Sonarqube
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./src/web-app
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_WEB_APP }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - uses: sonarsource/sonarqube-quality-gate-action@master
        timeout-minutes: 5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_WEB_APP }}
