apiVersion: apps/v1
kind: Deployment
metadata:
  name: accounts-deployment
  namespace: kwetter
  labels:
    app: accounts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: accounts
  template:
    metadata:
      namespace: kwetter
      labels:
        app: accounts
    spec:
      containers:
        - name: accounts
          image: vasilvelikovkwetter.azurecr.io/accounts
          ports:
            - containerPort: 4000
          env:
            - name: FIRESTORE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-api-key

            - name: FIRESTORE_AUTH_DOMAIN
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-auth-domain

            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-project-id

            - name: FIRESTORE_STORAGE_BUCKET
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-storage-bucket

            - name: FIRESTORE_MESSAGIN_SENDER_ID
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-messaging-sender-id

            - name: FIRESTORE_APP_ID
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-app-id

            - name: FIRESTORE_SERVICE_EMAIL
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-service-email

            - name: FIRESTORE_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: accounts-secret
                  key: firestore-service-password

            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: cluster-id

            - name: NATS_HOST
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: host

            - name: NATS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: port

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_ACCOUNT_CREATED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: account-created-channel
---
apiVersion: v1
kind: Service
metadata:
  name: accounts-service
  namespace: kwetter
spec:
  selector:
    app: accounts
  ports:
    - protocol: TCP
      port: 4001
      targetPort: 4000
