apiVersion: v1
kind: Secret
metadata:
  name: accounts-secret
  namespace: kwetter
type: Opaque
data:
  firestore-api-key: QUl6YVN5QV9USjRrcURtQW5pY1IxTlVhQW1fX05WV0xjSERkbWlB
  firestore-auth-domain: a3dldHRlci1hY2NvdW50cy5maXJlYmFzZWFwcC5jb20=
  firestore-project-id: a3dldHRlci1hY2NvdW50cw==
  firestore-storage-bucket: a3dldHRlci1hY2NvdW50cy5hcHBzcG90LmNvbQ==
  firestore-messaging-sender-id: MTA4NjIyODM2MzczMA==
  firestore-app-id: MToxMDg2MjI4MzYzNzMwOndlYjo3YjU5NGY4M2Y5NTYxNWUyN2IzMDBi
  firestore-service-email: YWNjb3VudHMtc2VydmljZUBrd2V0dGVyLmNvbQ==
  firestore-service-password: NzQ3OGZlNWNjMDQ0ZDA0NTU5ZDYwYTFlZGUzZWE2ZjBjNmY1NGFmOWNmMjg2NzZjNTE4YmI4MTY0ZDkxYTU1MGIzNGI1Y2ZjNWQxYTY3ZGRkMjBlZWYwNmNkMWE5NWVmZDc5MjkzNzU0NzljOGY5OGU0NTVlZjc4MDdkZTYyNDc=
