apiVersion: apps/v1
kind: Deployment
metadata:
  name: following-deployment
  labels:
    app: following
spec:
  replicas: 1
  selector:
    matchLabels:
      app: following
  template:
    metadata:
      labels:
        app: following
    spec:
      containers:
        - name: following
          image: kwetteracr.azurecr.io/following
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: FIRESTORE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: FIRESTORE_API_KEY

            - name: FIRESTORE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: FIRESTORE_AUTH_DOMAIN

            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: FIRESTORE_PROJECT_ID

            - name: FIRESTORE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: FIRESTORE_STORAGE_BUCKET

            - name: FIRESTORE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: FIRESTORE_MESSAGING_SENDER_ID

            - name: FIRESTORE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: FIRESTORE_APP_ID

            - name: FIRESTORE_SERVICE_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: FIRESTORE_SERVICE_EMAIL

            - name: FIRESTORE_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: following-secret
                  key: FIRESTORE_SERVICE_PASSWORD

            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: CLUSTER_ID

            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: URL

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_DURABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: NATS_DURABLE_NAME

            - name: NATS_QUEUE_GROUP
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: NATS_QUEUE_GROUP

            - name: NATS_ACCOUNT_CREATED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: ACCOUNT_CREATED_CHANNEL

            - name: NATS_ACCOUNT_DELETED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: ACCOUNT_DELETED_CHANNEL

            - name: NATS_USER_FOLLOWED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: USER_FOLLOWED_CHANNEL
---
apiVersion: v1
kind: Service
metadata:
  name: following-service
spec:
  selector:
    app: following
  ports:
    - protocol: TCP
      port: 4005
      targetPort: 4000
