apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: kwetteracr.azurecr.io/gateway
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
          env:
            - name: CLIENT_URL
              value: "*"

            - name: ACCOUNTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: accounts-config
                  key: URL

            - name: DETAILS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: details-config
                  key: URL

            - name: FOLLOWING_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: following-config
                  key: URL

            - name: LIKES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: likes-config
                  key: URL

            - name: MENTIONING_POSTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: mentioning-posts-config
                  key: URL

            - name: MENTIONS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: mentions-config
                  key: URL

            - name: PICTURES_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: pictures-config
                  key: URL

            - name: POSTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: posts-config
                  key: URL

            - name: TIMELINE_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: timeline-config
                  key: URL

            - name: TREND_POSTS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: URL

            - name: TRENDS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: URL

            - name: USERS_SERVICE_URL
              valueFrom:
                configMapKeyRef:
                  name: users-config
                  key: URL

            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: gateway-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 4000
      targetPort: 4000
