apiVersion: v1
kind: Secret
metadata:
  name: mentions-secret
  namespace: kwetter
type: Opaque
data:
  firestore-api-key: QUl6YVN5QWVuYnNzeWRxLVJ6R2M5cEJUbVJQal9kbWNka2haTnJj
  firestore-auth-domain: a3dldHRlci1tZW50aW9ucy5maXJlYmFzZWFwcC5jb20=
  firestore-project-id: a3dldHRlci1tZW50aW9ucw==
  firestore-storage-bucket: a3dldHRlci1tZW50aW9ucy5hcHBzcG90LmNvbQ==
  firestore-messaging-sender-id: Nzg5NTc4NzA1NTE1
  firestore-app-id: MTo3ODk1Nzg3MDU1MTU6d2ViOmQyYzQwOTZlYjMyN2M1YWM5NWRmMmU=
