apiVersion: v1
kind: ConfigMap
metadata:
  name: mentioning-posts-config
  namespace: kwetter
data:
  host: "http://mentioning-posts-service"
  port: "4004"
  nats-durable-name: mentioning-posts
  nats-queue-group: mentioning-posts-queue-group
