apiVersion: v1
kind: ConfigMap
metadata:
  name: mentioning-posts-config
data:
  URL: "http://mentioning-posts-service:4004"

  FIRESTORE_API_KEY: AIzaSyBvoAN9zv9TtAxWG4ZNXY_mcYm9IGd-mWw
  FIRESTORE_AUTH_DOMAIN: kwetter-mentioning-posts.firebaseapp.com
  FIRESTORE_PROJECT_ID: kwetter-mentioning-posts
  FIRESTORE_STORAGE_BUCKET: kwetter-mentioning-posts.appspot.com
  FIRESTORE_MESSAGING_SENDER_ID: "905059728564"
  FIRESTORE_APP_ID: 1:905059728564:web:ac275a3c92505ca1caebe1

  FIRESTORE_SERVICE_EMAIL: mentioning-posts-service@kwetter.com

  NATS_DURABLE_NAME: mentioning-posts
  NATS_QUEUE_GROUP: mentioning-posts-queue-group
