apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
  namespace: kwetter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      containers:
        - name: nats
          image: nats-streaming
          env:
            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: cluster-id

            - name: NATS_PORT
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: port

            - name: NATS_MONITORING_PORT
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: monitoring-port
          args: [
            '-p',
            '$(NATS_PORT)',
            '-m',
            '$(NATS_MONITORING_PORT)',
            '-hbi',
            '5s',
            '-hbt',
            '5s',
            '-hbf',
            '2',
            '-SD',
            '-cid',
            '$(NATS_CLUSTER_ID)'
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
  namespace: kwetter
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port: 4222
      targetPort: 4222

    - name: monitoring
      protocol: TCP
      port: 8222
      targetPort: 8222
