apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nats
  template:
    metadata:
      labels:
        app: nats
    spec:
      container:
        - name: nats
          image: nats-streaming:0.17.0
          env:
            - name: NATS_CLUSTER_ID
                valueFrom:
                  secretKeyRef:
                    name: nats-config
                    key: nats-cluster-id

            - name: NATS_PORT
              valueFrom:
                secretKeyRef:
                  name: nats-config
                  key: nats-port

            - name: NATS_MONITORING_PORT
              valueFrom:
                secretKeyRef:
                  name: nats-config
                  key: nats-monitoring-port
          args: [
            '-p',
            '$(NATS_PORT)',
            '-m',
            '$(NATS_MONITORING_PORT)',
            '-hbi',
            '5s',
            '-hbt',
            '5s',
            '-hbf',
            '2',
            '-SD',
            '-cid',
            '$(NATS_CLUSTER_ID)'
          ]
---
apiVersion: v1
kind: Service
metadata:
  name: nats-service
spec:
  selector:
    app: nats
  ports:
    - name: client
      protocol: TCP
      port:
        valueFrom:
          configMapKeyRef:
            name: nats-config
            key: nats-port
      targetPort: 4222

    - name: monitoring
      protocol: TCP
      port:
        valueFrom:
          configMapKeyRef:
            name: nats-config
            key: nats-monitoring-port
      targetPort: 8222
