apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
  namespace: kwetter
data:
  CLUSTER_ID: kwetter
  URL: "http://nats-service:4222"
  MONITORING_PORT: "8222"

  ACCOUNT_CREATED_CHANNEL: account:created
  ACCOUNT_PROMOTED_CHANNEL: account:promoted
  ACCOUNT_DEMOTED_CHANNEL: account:demoted
  ACCOUNT_DELETED_CHANNEL: account:deleted

  POST_CREATED_CHANNEL: post:created
  POST_LIKED_CHANNEL: post:liked
  POST_MENTIONED_CHANNEL: post:mentioned
  POST_TRENDED_CHANNEL: post:trended
  POST_DELETED_CHANNEL: post:deleted

  USER_FOLLOWED_CHANNEL: user:followed

  DETAILS_ADDED_CHANNEL: details:added

  PICTURE_ADDED_CHANNEL: picture:added

  MENTION_DELETED_CHANNEL: mention:deleted

  LIKE_DELETED_CHANNEL: like:deleted
