apiVersion: v1
kind: ConfigMap
metadata:
  name: posts-config
data:
  URL: "http://posts-service:4002"

  FIRESTORE_API_KEY: AIzaSyAQWZ54EG20YkVh0MQ1_CDeZUNRZs7pP4Y
  FIRESTORE_AUTH_DOMAIN: kwetter-posts-fc493.firebaseapp.com
  FIRESTORE_PROJECT_ID: kwetter-posts-fc493
  FIRESTORE_STORAGE_BUCKET: kwetter-posts-fc493.appspot.com
  FIRESTORE_MESSAGING_SENDER_ID: "254738211874"
  FIRESTORE_APP_ID: 1:254738211874:web:b3e3b1e59ff1a6811ad67b

  FIRESTORE_SERVICE_EMAIL: posts-service@kwetter.com

  NATS_DURABLE_NAME: posts
  NATS_QUEUE_GROUP: posts-queue-group
