apiVersion: apps/v1
kind: Deployment
metadata:
  name: trends-deployment
  labels:
    app: trends
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trends
  template:
    metadata:
      labels:
        app: trends
    spec:
      containers:
        - name: trends
          image: vjvkwetter.azurecr.io/trends
          ports:
            - containerPort: 4000
          resources:
            limits:
              cpu: 200m
            requests:
              cpu: 200m
          env:
            - name: FIRESTORE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: FIRESTORE_API_KEY

            - name: FIRESTORE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: FIRESTORE_AUTH_DOMAIN

            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: FIRESTORE_PROJECT_ID

            - name: FIRESTORE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: FIRESTORE_STORAGE_BUCKET

            - name: FIRESTORE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: FIRESTORE_MESSAGING_SENDER_ID

            - name: FIRESTORE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: FIRESTORE_APP_ID

            - name: FIRESTORE_SERVICE_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: FIRESTORE_SERVICE_EMAIL

            - name: FIRESTORE_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trends-secret
                  key: FIRESTORE_SERVICE_PASSWORD

            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: CLUSTER_ID

            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: URL

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_DURABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: NATS_DURABLE_NAME

            - name: NATS_QUEUE_GROUP
              valueFrom:
                configMapKeyRef:
                  name: trends-config
                  key: NATS_QUEUE_GROUP

            - name: NATS_POST_CREATED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: POST_CREATED_CHANNEL

            - name: NATS_POST_TRENDED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: POST_TRENDED_CHANNEL
---
apiVersion: v1
kind: Service
metadata:
  name: trends-service
spec:
  selector:
    app: trends
  ports:
    - protocol: TCP
      port: 4008
      targetPort: 4000
