apiVersion: apps/v1
kind: Deployment
metadata:
  name: trend-posts-deployment
  labels:
    app: trend-posts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trend-posts
  template:
    metadata:
      labels:
        app: trend-posts
    spec:
      containers:
        - name: trend-posts
          image: kwetteracr.azurecr.io/trend_posts
          ports:
            - containerPort: 4000
          env:
            - name: FIRESTORE_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: FIRESTORE_API_KEY

            - name: FIRESTORE_AUTH_DOMAIN
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: FIRESTORE_AUTH_DOMAIN

            - name: FIRESTORE_PROJECT_ID
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: FIRESTORE_PROJECT_ID

            - name: FIRESTORE_STORAGE_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: FIRESTORE_STORAGE_BUCKET

            - name: FIRESTORE_MESSAGING_SENDER_ID
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: FIRESTORE_MESSAGING_SENDER_ID

            - name: FIRESTORE_APP_ID
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: FIRESTORE_APP_ID

            - name: FIRESTORE_SERVICE_EMAIL
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: FIRESTORE_SERVICE_EMAIL

            - name: FIRESTORE_SERVICE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: trend-posts-secret
                  key: FIRESTORE_SERVICE_PASSWORD

            - name: NATS_CLUSTER_ID
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: CLUSTER_ID

            - name: NATS_URL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: URL

            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name

            - name: NATS_DURABLE_NAME
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: NATS_DURABLE_NAME

            - name: NATS_QUEUE_GROUP
              valueFrom:
                configMapKeyRef:
                  name: trend-posts-config
                  key: NATS_QUEUE_GROUP

            - name: NATS_POST_CREATED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: POST_CREATED_CHANNEL

            - name: NATS_POST_TRENDED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: POST_TRENDED_CHANNEL

            - name: NATS_POST_LIKED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: POST_LIKED_CHANNEL

            - name: NATS_POST_DELETED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: POST_DELETED_CHANNEL

            - name: NATS_LIKE_DELETED_CHANNEL
              valueFrom:
                configMapKeyRef:
                  name: nats-config
                  key: LIKE_DELETED_CHANNEL
---
apiVersion: v1
kind: Service
metadata:
  name: trend-posts-service
spec:
  selector:
    app: trend-posts
  ports:
    - protocol: TCP
      port: 4009
      targetPort: 4000
