apiVersion: v1
kind: ConfigMap
metadata:
  name: trend-posts-config
data:
  URL: "http://trend-posts-service:4009"

  FIRESTORE_API_KEY: AIzaSyC0yMl59GW2wAHBiz-22uaO5Q1QIXpcuTg
  FIRESTORE_AUTH_DOMAIN: kwetter-trend-posts.firebaseapp.com
  FIRESTORE_PROJECT_ID: kwetter-trend-posts
  FIRESTORE_STORAGE_BUCKET: kwetter-trend-posts.appspot.com
  FIRESTORE_MESSAGING_SENDER_ID: "1072639739979"
  FIRESTORE_APP_ID: 1:1072639739979:web:280cf99e06352f87e3a5ce

  FIRESTORE_SERVICE_EMAIL: trend-posts-service@kwetter.com

  NATS_DURABLE_NAME: trend-posts
  NATS_QUEUE_GROUP: trend-posts-queue-group
